GOOGLE_MAPS_API_BASE = "https://maps.googleapis.com/maps/api"
GOOGLE_MAPS_API_DISTANCE_URI = "/distancematrix/json"
GOOGLE_MAPS_DISTANCE_API = GOOGLE_MAPS_API_BASE + GOOGLE_MAPS_API_DISTANCE_URI
GOOGLE_MAPS_API_KEY = "AIzaSyC47xnB-Nqt4IFsJ675hMGUbPw6560iJCg"
GOOGLE_MAPS_KEY_URI = "key=" + GOOGLE_MAPS_API_KEY
OPTIMAL_DENSITY = 0.42
AGROMONITORING_API_BASE = "http://api.agromonitoring.com/agro/1.0"
AGROMONITORING_POLYGON_API = AGROMONITORING_API_BASE + "/polygons"
AGROMONITORING_NDVI_API = AGROMONITORING_API_BASE + "/ndvi/history?"
AGROMONITORING_API_KEY = "b5663a79a19a902ad50c8a81eb765fbe"
POLYGON_COORDS_BASE = "https://nominatim.openstreetmap.org/search.php?"
