GOOGLE_MAPS_API_BASE = "https://maps.googleapis.com/maps/api"
GOOGLE_MAPS_API_DISTANCE_URI = "/distancematrix/json"
GOOGLE_MAPS_DISTANCE_API = GOOGLE_MAPS_API_BASE + GOOGLE_MAPS_API_DISTANCE_URI
GOOGLE_MAPS_API_KEY = "AIzaSyC47xnB-Nqt4IFsJ675hMGUbPw6560iJCg"
GOOGLE_MAPS_KEY_URI = "key=" + GOOGLE_MAPS_API_KEY
OPTIMAL_DENSITY = 0.0222